tap "apple/apple", "http://github.com/apple/homebrew-apple"
tap "belkadan/apps", "https://belkadan.com/source/homebrew-apps"
tap "browsh-org/browsh"
tap "gcenx/wine"
tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "kiliankoe/formulae"
tap "mono0926/license-plist"
tap "peripheryapp/periphery"
tap "robotsandpencils/made"
tap "swiftdocorg/formulae"
tap "thoughtbot/formulae"
tap "vapor/tap"
brew "act"
brew "aircrack-ng"
brew "gettext"
brew "aria2"
brew "asdf"
brew "bash-completion"
brew "bat"
brew "boost"
brew "bsdmake"
brew "fontconfig"
brew "chezmoi"
brew "cloc"
brew "cmake"
brew "curl"
brew "dbus"
brew "dbus-glib"
brew "diff-so-fancy"
brew "direnv"
brew "eza"
brew "fd"
brew "fish"
brew "gd"
brew "gh"
brew "git"
brew "git-lfs"
brew "git-trim"
brew "gource"
brew "librsvg"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hyperfine"
brew "imagemagick"
brew "oniguruma"
brew "jq"
brew "less"
brew "mas"
brew "mitmproxy"
brew "ncdu"
brew "ossp-uuid"
brew "parallel"
brew "pkg-config"
brew "prettyping"
brew "proctools"
brew "shellcheck"
brew "sourcery"
brew "swift-format"
brew "swift-protobuf"
brew "swiftformat"
brew "swiftlint"
brew "telnet"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tokei"
brew "wget"
brew "xcbeautify"
brew "browsh-org/browsh/browsh"
brew "getsentry/tools/sentry-cli"
brew "kiliankoe/formulae/swift-outdated"
brew "mono0926/license-plist/license-plist"
brew "robotsandpencils/made/xcodes"
cask "1password"
cask "1password-cli"
cask "8bitdo-ultimate-software"
cask "altserver"
cask "bartender"
cask "battle-net"
cask "brave-browser"
cask "charles"
cask "daisydisk"
cask "dash"
cask "devtoys"
cask "discord"
cask "dropbox"
cask "duckduckgo"
cask "firefox"
cask "font-awesome-terminal-fonts"
cask "font-cascadia-code"
cask "font-cascadia-code-pl"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-inconsolata"
cask "font-input"
cask "font-monocraft"
cask "fork"
cask "gitup"
cask "gog-galaxy"
cask "gzdoom"
cask "imazing"
cask "itch"
cask "iterm2"
cask "little-snitch"
cask "macdown"
cask "micro-snitch"
cask "microblog"
cask "mimestream"
cask "minecraft"
cask "mockoon"
cask "monodraw"
cask "netnewswire"
cask "openemu"
cask "p4v"
cask "paw"
cask "periphery"
cask "postman"
cask "protonvpn"
cask "provisionql"
cask "raspberry-pi-imager"
cask "retroarch-metal"
cask "rocket"
cask "scroll-reverser"
cask "secretive"
cask "sf-symbols"
cask "signal"
cask "sketch"
cask "slack"
cask "spotify"
cask "stats"
cask "steam"
cask "sublime-merge"
cask "teamviewer"
cask "telegram"
cask "tor-browser"
cask "trailer"
cask "transmission"
cask "vanilla"
cask "visual-studio-code"
cask "vlc"
cask "wineskin"
cask "wwdc"
cask "xcodes"
cask "zoom"
mas "1Blocker", id: 1365531024
mas "1Password for Safari", id: 1569813296
mas "Actions", id: 1586435171
mas "Amphetamine", id: 937984704
mas "BetterSnapTool", id: 417375580
mas "Boop", id: 1518425043
mas "Buildwatch", id: 1523347474
mas "Deliveries", id: 290986013
mas "Dependencies", id: 1538972026
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "Display Menu", id: 549083868
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "FANTASIAN", id: 1517339045
mas "Finity", id: 1071698434
mas "Ivory", id: 6444602274
mas "Keynote", id: 409183694
mas "Kingdom Rush Frontiers+", id: 1579364157
mas "LightBlue", id: 557428110
mas "MeetingBar", id: 1532419400
mas "Microsoft Remote Desktop", id: 1295203466
mas "Mini Motorways", id: 1456188526
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PikaDex", id: 1509561856
mas "Playgrounds", id: 1496833156
mas "Pocket", id: 568494494
mas "pullBar", id: 1601913905
mas "RocketSim", id: 1504940162
mas "Save to Pocket", id: 1477385213
mas "Shareful", id: 1522267256
mas "SourceryPro", id: 1561780836
mas "Steam Link", id: 1246969117
mas "TestFlight", id: 899247664
mas "ToothFairy", id: 1191449274
mas "Twitter", id: 1482454543
mas "WireGuard", id: 1451685025
vscode "christian-kohler.npm-intellisense"
vscode "codezombiech.gitignore"
vscode "DavidAnson.vscode-markdownlint"
vscode "donjayamanne.githistory"
vscode "EditorConfig.EditorConfig"
vscode "EFanZh.graphviz-preview"
vscode "eriklynd.json-tools"
vscode "esbenp.prettier-vscode"
vscode "felipecaputo.git-project-manager"
vscode "fisheva.eva-theme"
vscode "fwcd.kotlin"
vscode "geeklearningio.graphviz-markdown-preview"
vscode "ginfuru.ginfuru-vscode-jekyll-syntax"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "GrapeCity.gc-excelviewer"
vscode "IBM.output-colorizer"
vscode "jasonnutter.vscode-codeowners"
vscode "kevinkyang.auto-comment-blocks"
vscode "kumar-harsh.graphql-for-vscode"
vscode "mariomatheu.syntax-project-pbxproj"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "mxschmitt.postscript"
vscode "Orta.playdate"
vscode "PKief.material-icon-theme"
vscode "quicktype.quicktype"
vscode "rebornix.ruby"
vscode "rust-lang.rust-analyzer"
vscode "serayuzgur.crates"
vscode "shakram02.bash-beautify"
vscode "sidneys1.gitconfig"
vscode "skyapps.fish-vscode"
vscode "sswg.swift-lang"
vscode "Stephanvs.dot"
vscode "sumneko.lua"
vscode "tamasfe.even-better-toml"
vscode "timonwong.shellcheck"
vscode "twxs.cmake"
vscode "Tyriar.sort-lines"
vscode "vadimcn.vscode-lldb"
vscode "wingrunr21.vscode-ruby"
