tap "browsh-org/browsh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "peripheryapp/periphery"
tap "thoughtbot/formulae"
tap "vapor/tap"
brew "sqlite"
brew "aircrack-ng"
brew "autoconf"
brew "libtool"
brew "libyaml"
brew "asdf"
brew "bash-completion"
brew "bat"
brew "boost"
brew "bsdmake"
brew "fontconfig"
brew "gettext"
brew "carthage"
brew "cloc"
brew "cmake"
brew "curl"
brew "diff-so-fancy"
brew "fd"
brew "fish"
brew "gd"
brew "gh"
brew "git"
brew "git-lfs"
brew "gource"
brew "graphviz"
brew "hub"
brew "hugo"
brew "hyperfine"
brew "imagemagick"
brew "oniguruma"
brew "jq"
brew "librsvg"
brew "mas"
brew "mint"
brew "mitmproxy"
brew "ncdu"
brew "ninja"
brew "parallel"
brew "pkg-config"
brew "prettyping"
brew "proctools"
brew "shellcheck"
brew "sourcekitten"
brew "sourcery"
brew "swiftlint"
brew "thefuck"
brew "tldr"
brew "wget"
brew "xcodegen"
brew "browsh-org/browsh/browsh"
brew "thoughtbot/formulae/rcm"
cask "1password"
cask "boostnote"
cask "brave-browser"
cask "calibre"
cask "daisydisk"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "fastlane"
cask "firefox"
cask "font-awesome-terminal-fonts"
cask "font-fira-code"
cask "font-hack"
cask "font-inconsolata"
cask "font-input"
cask "font-sans-forgetica"
cask "fork"
cask "gitup"
cask "gog-galaxy"
cask "gpg-suite"
cask "itch"
cask "iterm2"
cask "java"
cask "keepassx"
cask "keybase"
cask "libreoffice"
cask "little-snitch"
cask "macdown"
cask "micro-snitch"
cask "microblog"
cask "minecraft"
cask "monodraw"
cask "openemu"
cask "p4v"
cask "paw"
cask "periphery"
cask "postman"
cask "powershell"
cask "racket"
cask "retroarch"
cask "rocket"
cask "safari-technology-preview"
cask "scroll-reverser"
cask "sony-ps4-remote-play"
cask "spotify"
cask "station"
cask "steam"
cask "sublime-merge"
cask "textual"
cask "tor-browser"
cask "transmission"
cask "twitch"
cask "vanilla"
cask "visual-studio-code"
cask "whalebird"
cask "wwdc"
mas "1Blocker", id: 1107421413
mas "Battery Health 2", id: 1120214373
mas "BetterSnapTool", id: 417375580
mas "CCMenu", id: 603117688
mas "Crossy Road Castle", id: 1489275350
mas "Deckset", id: 847496013
mas "DevCleaner", id: 1388020431
mas "GarageBand", id: 682658836
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "MarsEdit", id: 1198319098
mas "Microsoft Remote Desktop", id: 1295203466
mas "Mini Motorways", id: 1456188526
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paste JSON as Code • quicktype", id: 1330801220
mas "Playgrounds", id: 1496833156
mas "Pocket", id: 568494494
mas "Save to Pocket", id: 1477385213
mas "ToothFairy", id: 1191449274
mas "Trello", id: 1278508951
mas "Tweetbot", id: 1384080005
mas "Tweetbot", id: 557168941
mas "Twitter", id: 1482454543
